// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealtimeDashboard.Infrastructure.Persistence;

#nullable disable

namespace RealtimeDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("RealtimeDashboard.Domain.Entities.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Metrics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ccd0dc7-d73c-41b0-a734-222d00e25bdc"),
                            Category = 1,
                            Key = "active_users",
                            Label = "Active users",
                            Unit = "#",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("1ccd0dc7-d73c-41b0-a734-222d00e25bdc"),
                            Category = 2,
                            Key = "orders_today",
                            Label = "Orders today",
                            Unit = "#",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("2ccd0dc7-d73c-41b0-a734-222d00e25bdc"),
                            Category = 2,
                            Key = "revenue_today",
                            Label = "Income today",
                            Unit = "$",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("3ccd0dc7-d73c-41b0-a734-222d00e25bdc"),
                            Category = 3,
                            Key = "ai_tasks_queue",
                            Label = "AI task in queu",
                            Unit = "#",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("4ccd0dc7-d73c-41b0-a734-222d00e25bdc"),
                            Category = 3,
                            Key = "ai_tasks_done",
                            Label = "AI task done",
                            Unit = "#",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("5ccd0dc7-d73c-41b0-a734-222d00e25bdc"),
                            Category = 4,
                            Key = "cpu_usage",
                            Label = "CPU loading",
                            Unit = "%",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
